services:
  - type: web
    name: notes-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5000
